const express = require('express')
const router = express.Router()
const { login, logout, getMe, updateProfile, signup, authCallback, inviteAgent, validateToken, signupWithToken, getInvites, cancelInvite, forgotPassword, resetPassword, agreeTos } = require('../controllers/authController')
const { authMiddleware, authMiddlewareNoTos } = require('../middleware/auth')

router.post('/login', login)
router.post('/signup', signup)
router.post('/signup-invite', signupWithToken)
router.post('/logout', logout)
router.get('/me', authMiddleware, getMe)
router.put('/profile', authMiddleware, updateProfile)
router.post('/invite', authMiddleware, inviteAgent)
router.get('/invites', authMiddleware, getInvites)
router.delete('/invites/:id', authMiddleware, cancelInvite)
router.get('/validate-token/:token', validateToken)
router.get('/callback', authCallback)
router.post('/forgot-password', forgotPassword)
router.post('/reset-password', resetPassword)
router.post('/agree-tos', authMiddlewareNoTos, agreeTos)

module.exports = router
